CITY_NAMES = [
    "Augustów",
    "Biała",
    "Biała Podlaska",
    "Białystok",
    "Bielsko-Biała",
    "Borówiec",
    "Borsukowizna",
    "Brzeg",
    "Bydgoszcz",
    "Bytów",
    "Chełm",
    "Chojnów",
    "Ciechocinek",
    "Cieszyn",
    "Częstochowa",
    "Czerniawa",
    "Dąbrowa Górnicza",
    "Dębica",
    "Diabla Góra",
    "Dusznik-Zdrój",
    "Dzierżoniów",
    "Ełk",
    "Florianka",
    "Gajew",
    "Gdańsk",
    "Gdynia",
    "Giżycko",
    "Gliwice",
    "Głubczyce",
    "Goczałkowice-Zdrój",
    "Gołdap",
    "Gołuchów",
    "Gorzów Wielkopolski",
    "Grudziądz",
    "Guty Duże",
    "Inowrocław",
    "Jarosław",
    "Jasło",
    "Jastrzębie-Zdrój",
    "Jelenia Góra",
    "Kalisz",
    "Kaszów",
    "Katowice",
    "Kędzierzyn-Koźle",
    "Kielce",
    "Kluczbork",
    "Kłodzko",
    "Kołobrzeg",
    "Koniczynka",
    "Konin",
    "Konstancin-Jeziorna",
    "Koszalin",
    "Koziegłowy",
    "Kraków",
    "Krapkowice",
    "Krempna",
    "Krosno",
    "Krotoszyn",
    "Krzyżówka",
    "Legionowo",
    "Legnica",
    "Lębork",
    "Łagów",
    "Łask",
    "Łeba",
    "Łomża",
    "Łódź",
    "Małogoszcz",
    "Malbork",
    "Mielec",
    "Mosina",
    "Myślenice",
    "Nakło nad Notecią",
    "Niepołomice",
    "Nisko",
    "Nowa Ruda",
    "Nowa Sól",
    "Nowiny",
    "Nowy Sącz",
    "Nowy Targ",
    "Nysa",
    "Olesno",
    "Olkusz",
    "Olsztyn",
    "Oława",
    "Opole",
    "Osieczów",
    "Ostróda",
    "Ostrołęka",
    "Oświęcim",
    "Parzniewice",
    "Pabianice",
    "Piastów",
    "Piła",
    "Piotrków Trybunalski",
    "Płock",
    "Pleszew",
    "Połaniec",
    "Poznań",
    "Przemyśl",
    "Radom",
    "Radomsko",
    "Racibórz",
    "Rabka-Zdrój",
    "Rymanów-Zdrój",
    "Rybnik",
    "Rzeszów",
    "Sanok",
    "Siedlce",
    "Skawina",
    "Skarżysko-Kamienna",
    "Słupsk",
    "Smolary Bytnickie",
    "Sopot",
    "Sosnowiec",
    "Starachowice",
    "Suwałki",
    "Sucha Beskidzka",
    "Sulechów",
    "Sulęcin",
    "Swinoujście",
    "Szarów",
    "Szczecin",
    "Szczecinek",
    "Szymbark",
    "Świecie",
    "Świnoujście",
    "Tarnobrzeg",
    "Tarnów",
    "Tomaszów Lubelski",
    "Toruń",
    "Trzebinia",
    "Trzebnica",
    "Tychy",
    "Ustroń",
    "Uście Gorlickie Wysowa",
    "Wałbrzych",
    "Warszawa",
    "Widuchowa",
    "Wilczopole",
    "Włocławek",
    "Wodzisław Śląski",
    "Wrocław",
    "Wschowa",
    "Wysokie Mazowieckie",
    "Zabrze",
    "Zabierzów",
    "Zakopane",
    "Zamość",
    "Zawiercie",
    "Zdzieszowice",
    "Zielona Góra",
    "Zielonka",
    "Złockie",
    "Złoty Potok",
    "Żary",
    "Żyrardów"
]